### ISSUE TITLE
Training code :)

### ISSUE THREAD

**Issue by christophschuhmann** [fudan-generative-vision/hallo#29] opened 2024-06-16 19:18 UTC
Would you please be so kind and also release the training code? :)

**Comment by Inferencer** [comment] 2024-06-16 21:33
They will release in two weeks https://github.com/fudan-generative-vision/hallo/issues/18

**Comment by AricGamma** [comment] 2024-06-18 14:30
Duplicate of #18

**Comment by AricGamma** [comment] 2024-07-22 01:43
Closing this issue. If any other questions, please open a new one.

**Closed by AricGamma** 2024-07-22 01:43 UTC
