### ISSUE TITLE
Windows inference

### ISSUE THREAD

**Issue by hexdrx** [fudan-generative-vision/hallo#24] opened 2024-06-16 13:57 UTC
Hello everyone!
Can I run it on windows machine?

**Comment by Inferencer** [comment] 2024-06-16 16:55
> Hello everyone! Can I run it on windows machine?

Yeah there is a windows fork

**Comment by AricGamma** [comment] 2024-06-18 14:29
Duplicate of #39

**Comment by yjktech** [comment] 2024-06-19 05:36
thx for sharing

**Comment by AricGamma** [comment] 2024-06-20 06:41
We've tested on Windows 11, Cuda 12.1. It works well.

**Closed by AricGamma** 2024-06-20 06:41 UTC
